#pragma once
#define VOXCRAFT_VERSION_MAJOR 0
#define VOXCRAFT_VERSION_MINOR 0
#define VOXCRAFT_VERSION_PATCH 1
#define VOXCRAFT_BUILD_NUMBER 48
#define VOXCRAFT_BUILD_DATE "2025-10-15 16:25:40"
#define VOXCRAFT_BUILD_TYPE "Debug"
#define VOXCRAFT_VERSION_STR "0.0.1"
#define VOXCRAFT_VERSION_FULL_STR "0.0.1.48"
